config/routes.rb
Standup::Application.routes.draw do
  resources :quick_stands

end

app/models/quick_stand.rb
class QuickStand < ActiveRecord::Base
  attr_accessible :blockers, :developer, :did_yesterday, :do_today, :email, :notes, :rating, :created_at
    validates_inclusion_of :rating,
    :in => 1..3, :message => "must be between 1 and 3"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quick_stands_controller.rb
class QuickStandsController < ApplicationController
  # GET /quick_stands
  # GET /quick_stands.json
  def index
    @quick_stands = QuickStand.all
    @q = QuickStand.search(params[:q])
    @quick_stands = @q.result.order("created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quick_stands }
    end
  end

  # GET /quick_stands/1
  # GET /quick_stands/1.json
  def show
    @quick_stand = QuickStand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quick_stand }
    end
  end

  # GET /quick_stands/new
  # GET /quick_stands/new.json
  def new
    @quick_stand = QuickStand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quick_stand }
    end
  end

  # GET /quick_stands/1/edit
  def edit
    @quick_stand = QuickStand.find(params[:id])
  end

  # POST /quick_stands
  # POST /quick_stands.json
  def create
    @quick_stand = QuickStand.new(params[:quick_stand])

    respond_to do |format|
      if @quick_stand.save
        format.html { redirect_to @quick_stand, notice: 'Quick stand was successfully created.' }
        format.json { render json: @quick_stand, status: :created, location: @quick_stand }
      else
        format.html { render action: "new" }
        format.json { render json: @quick_stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quick_stands/1
  # PUT /quick_stands/1.json
  def update
    @quick_stand = QuickStand.find(params[:id])

    respond_to do |format|
      if @quick_stand.update_attributes(params[:quick_stand])
        format.html { redirect_to @quick_stand, notice: 'Quick stand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quick_stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quick_stands/1
  # DELETE /quick_stands/1.json
  def destroy
    @quick_stand = QuickStand.find(params[:id])
    @quick_stand.destroy

    respond_to do |format|
      format.html { redirect_to quick_stands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quick_stands_helper.rb
module QuickStandsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quick Stand</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quick_stands/_form.html.erb
<style>
  div {
    display: inline-block;
  }
</style>
<%= form_for(@quick_stand) do |f| %>
  <% if @quick_stand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quick_stand.errors.count, "error") %> prohibited this quick_stand from being saved:</h2>

      <ul>
      <% @quick_stand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :do_today %><br />
    <%= f.text_area :do_today %>
  </div>
  <div class="field">
    <%= f.label :did_yesterday %><br />
    <%= f.text_area :did_yesterday %>
  </div>
  <div class="field">
    <%= f.label :blockers %><br />
    <%= f.text_area :blockers %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :developer %><br />
    <%= f.text_field :developer %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quick_stands/edit.html.erb
<h1>Editing quick_stand</h1>

<%= render 'form' %>

<%= link_to 'Show', @quick_stand %> |
<%= link_to 'Back', quick_stands_path %>

app/views/quick_stands/index.html.erb
<h1>Listing quick_stands</h1>

<table>
  <tr>
    <th>Created_at</th>
    <th>Developer</th>
    <th>Do today</th>
    <th>Did yesterday</th>
    <th>Blockers</th>
    <th>Notes</th>
    <th>Rating</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%= search_form_for @q do |f| %>
  <%= f.label :developer_cont %>
  <%= f.text_field :developer_cont %>

  <%= f.submit %>
<% end %>
<% @quick_stands.each do |quick_stand| %>
  <tr>
    <td><b><%= quick_stand.created_at.strftime("%A, %B #{quick_stand.created_at.day.ordinalize}, %Y") %></b></td>
    <td><%= quick_stand.developer %></td>
    <td><%= quick_stand.do_today %></td>
    <td><%= quick_stand.did_yesterday %></td>
    <td><%= quick_stand.blockers %></td>
    <td><%= quick_stand.notes %></td>
    <td ALIGN="CENTER" class="rating"><%= quick_stand.rating %></td>
    <td><a href ='mailto:<%= quick_stand.email %>'><%= quick_stand.email %></a></td>
    <td><%= link_to 'Show', quick_stand %></td>
    <td><%= link_to 'Edit', edit_quick_stand_path(quick_stand) %></td>
    <td><%= link_to 'Destroy', quick_stand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quick stand', new_quick_stand_path %>
<script type="text/javascript">
$('document').ready( function () {
    
    $.each($('tr td:nth-child(7)'), function() { if ($(this).text() == "3") $(this).css("background-color", "green")});
    $.each($('tr td:nth-child(7)'), function() { if ($(this).text() == "2") $(this).css("background-color", "yellow")});
    $.each($('tr td:nth-child(7)'), function() { if ($(this).text() == "1") $(this).css("background-color", "red")});
    $('.rating').html(function(i, v){
    return v.replace(/(\d)/g, '<img width="20px" src=' + '/assets/' + '$1.png />');
});

});
</script>

app/views/quick_stands/new.html.erb
<h1>New quick_stand</h1>

<%= render 'form' %>

<%= link_to 'Back', quick_stands_path %>

app/views/quick_stands/show.html.erb
<p id="notice"><%= notice %></p>
=============== <%= @quick_stand.created_at.strftime("%A, %B #{@quick_stand.created_at.day.ordinalize}, %Y") %> ===================
<p>
  <b>Developer:</b>
  <%= @quick_stand.developer %>
</p>

<p>
  <b>Did yesterday:</b>
  <%= @quick_stand.did_yesterday %>
</p>

<p>
  <b>Do today:</b>
  <%= @quick_stand.do_today %>
</p>

<p>
  <b>Blockers:</b>
  <%= @quick_stand.blockers %>
</p>

<p>
  <b>Cards and Notes:</b>
  <%= @quick_stand.notes %>
</p>

<p>
  <b>Rating:</b>
  <%= @quick_stand.rating %>
</p>

<p>
  <b>Email:</b>
  <%= @quick_stand.email %>
</p>
======================================================
<br/>
<%= link_to 'Edit', edit_quick_stand_path(@quick_stand) %> |
<%= link_to 'Back', quick_stands_path %>